### ISSUE TITLE
leader key

### ISSUE THREAD

**Issue by quantum-booty** [ianhi/jupyterlab-vimrc#11]
Is leader key possible? I tried to use \<SPACE\> in nmap but it does not work.

**Comment by ianhi** [comment]
Sadly no. Jupyterlab uses the codemirror editor and it's vim mode does not yet have a leader key. See https://github.com/codemirror/CodeMirror/issues/2841

Also from that issue:
> The Vim bindings are without a maintainer at the moment, so don't hold your breath waiting for new features.

**Comment by quantum-booty** [comment]
Thank you
