### ISSUE TITLE
clipboard support not included

### ISSUE THREAD

**Issue by fsondej** [ianhi/jupyterlab-vimrc#16]
jupyterlab_vim-system-clipboard-support isn't included, as the README says, and has to be installed separately

**Comment by ianhi** [comment]
woops i got a bit ahead of myself with pushing changes for jlab3. It's included in the extension for jlab3 but not for jlab2. Sorry about that - will add a note to the readme clarifying this. 

I'm also open to PRs that backporting clipboard support to the jlab-2 branch https://github.com/ianhi/jupyterlab-vimrc/tree/jlab-2
