### ISSUE TITLE
For < 2.0?

### ISSUE THREAD

**Issue by bs** [ianhi/jupyterlab-vimrc#2]
Is it possible to build for 1.x, or is this too dependent on 2.0 APIs?

**Comment by ianhi** [comment]
Currently no, but it shouldn't be too complicated to fix. I will try to get to this, but if you feel inspired then a PR against the freshly made `jlab-1` branch would be welcome :)

There are two problems that basically amount to doing the inverse of this guide: https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#updating-former-jupyterlab-coreutils-imports

1. Import setting registry from coreutils:
https://github.com/ianhi/jupyterlab-vimrc/blob/3055a7fa0fde1c5160fbbda231f37b65a58e8455/src/index.ts#L9

2. Modify the dependencies 
https://github.com/ianhi/jupyterlab-vimrc/blob/3055a7fa0fde1c5160fbbda231f37b65a58e8455/package.json#L36-L39

in particular `jupyterlab/application` should probably go to `^1.0.0` and coreutils may also need to be changed but I'm not sure. See also: https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#upgrading-library-versions

**Comment by ianhi** [comment]
Ok should be fixed on the [jlab1](https://github.com/ianhi/jupyterlab-vimrc/tree/jlab-1) branch. You can install with either:

npm tag:
`jupyter labextension install jupyterlab-vimrc@jlab1`
or version number
`jupyter labextension install jupyterlab-vimrc@0.1.1`

if it doesn't work please let me know

**Comment by ianhi** [comment]
thanks for pointing this out btw! I had never considered this

**Comment by bs** [comment]
Amazing! Thank you for your work! <3

I installed 2.X locally to test but haven't gotten around to poking yet. Will report back.

**Comment by ianhi** [comment]
I'm going to call this fixed and note that i don't think jlab 1.x is supported by jlab devs anymore. They are focused on 3.x and will probably still fix things in 2.x

**Comment by bs** [comment]
💪

I am using 2.0 now so all good on my end. The reason I hit it in the first place is that GCP defaults to a 1.X install, FYI!
