### ISSUE TITLE
Leaving insert mode no longer works

### ISSUE THREAD

**Issue by dcervenkov** [ianhi/jupyterlab-vimrc#21]
I'm on JupyterLab 3.1.18 and jupyterlab-vimrc 0.5.2. When I use the default `ii` keybinding to `<ESC>` to leave the insert mode, the `ii` characters get deleted but I'm left in insert mode.

I wonder if this issue might be related? https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/31

**Comment by dcervenkov** [comment]
Yes! It fixes it for me too. It seems the vim plugin keybindings are case sensitive (while vim isn't - even `<eSC>` works there). Thanks for looking into it! May I suggest adding a disclaimer about this to the default settings file?

**Comment by ianhi** [comment]
> Yes! It fixes it for me too. It seems the vim plugin keybindings are case sensitive (while vim isn't - even <eSC> works there). Thanks for looking into it! May I suggest adding a disclaimer about this to the default settings file?

PRs welcome of course :) but also is there language that would have been most helpful to you?

**Comment by ianhi** [comment]
closing so I don' see this issue and get that sinking heart feeling again (like I just did)

**Comment by dcervenkov** [comment]
#23 adds a short sentence about case sensitivity.
