### ISSUE TITLE
Donation Page

### ISSUE THREAD

**Issue by Pipboyguy** [ianhi/jupyterlab-vimrc#27]
@ianhi Is there a donation page for this repo? I'm there are a lot of vimrc users who would like this project to receive some extra love.

**Comment by ianhi** [comment]
Hi @Pipboyguy sorry i missed this last year. There was not though I appreciate the ask. Unfortunately then (and now) grad school is consumes most of my time so money is not the limiting factor on contributions. 

Happily most of this extension is now contained in `jupyterlab-vim`! thanks to efforts of other contributors :)
