### ISSUE TITLE
Update to be compatible with JupyterLab 4

### ISSUE THREAD

**Issue by joelostblom** [ianhi/jupyterlab-vimrc#29]
It would be great to be able to use this extension with jl 4, but when I install it, it automatically downgrades jl to 3.6

**Comment by Pipboyguy** [comment]
This repo seems to be unmaintained - I'd suggest looking into the latest juyterlab-vim extra key-binding capabilities https://github.com/jupyterlab-contrib/jupyterlab-vim/issues/113#issue-1909062806

**Comment by ianhi** [comment]
Hi @joelostblom I think most of the functionality of this extension has now made it's way in jupyterlab-vim proper. It provided three piece of functionality:

1. remapping keys
2. yanking to the system clipboard
3. allowing for `set unnamedplus=true`


of these, both 1 and 2 are now available from the main extension. and 3 is an upstream issue (opened by you I see :) ).


I think I will update the readme to make this clear so as not to confuse anyone. As it stands I have no intention of updating this repo for jlab4+ as I don't think that would provide any additional value to the community over the jupyterlab-vim extension.

**Comment by joelostblom** [comment]
Great, thanks for clarifying @ianhi !
