### ISSUE TITLE
Cannot disable default ii map

### ISSUE THREAD

**Issue by lukelbd** [ianhi/jupyterlab-vimrc#3]
I'm not sure there's any way to disable your default `ii` mapping. I tried an `inoremap` mapping of `ii` to `ii` but that does not seem to work (I'm guessing due to the limits of non-recursive mapping as you noted in your README). And of course an `imap` of `ii` to `ii` leads to recursion. Would you consider shipping without the default `ii` map since it cannot be overridden?

(Awesome package by the way!)

**Comment by ianhi** [comment]
Thanks for bringing this up - apparently I saw the error in my ways of foisting my vim preference on others 14 days ago and removed this default with https://github.com/ianhi/jupyterlab-vimrc/commit/45c348d5f75e0d4b7975931ff9e51e6f7da007e2 but never actually released this.

I just published version 0.3.0 so if you update the default should be gone. 

> (Awesome package by the way!)

Thanks 🙂
