### ISSUE TITLE
Make the cell of jupyter-notebook remember their mode

### ISSUE THREAD

**Issue by gordonrust** [ianhi/jupyterlab-vimrc#9]
@ianhi I am using your plugins together with @axelfahy/jupyterlab-vim. The problem with jupyterlab-vim is when I jump to a notebook cell, I always end up in the normal mode, even if that cell was in insert mode previously. Somewhere you have mentioned that each of these cells are seperate codemirror editors. Now, do you think it is possible to make the cell remember their states.

**Comment by ianhi** [comment]
Hi @gordonrust I see that you asked the same question on axelfahy's repo https://github.com/axelfahy/jupyterlab-vim/issues/13. 

It's a good question! But I think it makes more sense in the context of the other repo so I'll try to answer there
